name: pure
description: Functional programming essentials for Dart. Tail call optimization, partial application, memoization, and more.
version: 0.1.1
maintainer: Yakov Karpov (@purplenoodlesoop)

homepage: https://github.com/purplenoodlesoop/pure

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.10.0
